.TH lsusb 8 "19 November 2003" "usbutils-0.11" "Linux USB Utilities"
.IX lsusb
.SH NAME
lsusb \- list all USB devices
.SH SYNOPSIS
.B lsusb
[
.I options
]
.SH DESCRIPTION
.B lsusb
is a utility for displaying information about all USB buses in the system and
all devices connected to them.

To make use of all the features of this program,
you need to have a Linux kernel
which supports the /proc/bus/usb interface
(e.g., Linux kernel 2.3.15 or newer).

.SH OPTIONS
.TP
.B \-v
Tells
.I lsusb
to be verbose and display detailed information about all devices.
You must be root for this to work.
.TP
.B \-vv
Tells
.I lsusb
to be very verbose and display even more information (actually everything the
USB device is able to tell).
You must be root for this to work.
.TP
\fB\-s\fP [[\fIbus\fP]\fB:\fP][\fIdevnum\fP]
Show only devices in specified
.I bus
and/or
.I devnum.
Both ID's are given in hexadecimal and may be omitted.
.TP
\fB\-d\fP [\fIvendor\fP]\fB:\fP[\fIproduct\fP]
Show only devices with the specified vendor and product ID.
Both ID's are given in hexadecimal.
.TP
.B \-D \fIdevice\fP
Do not scan the /proc/bus/usb directory,
instead display only information
about the device whose device file is given.
The device file should be something like /proc/bus/usb/001/001.
This option displays detailed information;
you must be root to do this.
.TP
.B \-t
Tells
.I lsusb
to dump the physical USB device hierarchy as a tree.
.TP
.B \-x
This option is reserved for future use.
.TP
.B \-V, \-\-version
Print  version information on standard output,
then exit successfully.

.SH DIAGNOSTICS
.TP
cannot open /proc/bus/usb/\fInnn\fP/\fInnn\fP, Permission denied (13)
To get detailed information,
.I lsusb
must open the files in /proc/bus/usb in read-write mode.
You must be root in order to do this.

.SH RETURN VALUE
If the specified device is not found, a non-zero exit code is returned.

.SH FILES
.TP
.B /usr/share/misc/usb.ids
A list of all known USB ID's (vendors, products, classes, subclasses and protocols).
.TP
.B /proc/bus/usb
An interface to USB devices provided by the post-2.3.15 Linux
kernels. Contains per-bus subdirectories with per-device files and a
.I devices
file containing a list of all USB devices.
This interface is also support by some 2.2 Linux kernels.

.SH SEE ALSO
.BR lspci (8)

.SH AUTHOR
Thomas Sailer, <sailer@ife.ee.ethz.ch>.
