# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
# SPDX-FileCopyrightText: 2024 Lucas De Marchi <lucas.de.marchi@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: 'setup Alpine'
description: 'Setup an Alpine container for running CI'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: sh
      run: |
        apk update
        apk add \
          build-base \
          clang \
          eudev-dev \
          git \
          libusb-dev \
          linux-headers \
          meson
