#!/bin/sh
# SPDX-FileCopyrightText: 2026 Greg Kroah-Hartman <gregkh@linuxfoundation.org>
#
# SPDX-License-Identifier: GPL-2.0-only
set -eu
DIR="$(dirname "$(realpath "$0")")"
exec "$DIR/brat/bin/brat" "$@" "$DIR"/*.brat
