# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Check code style with clang-format

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: git fetch --depth=1 origin ${{ github.event.pull_request.base.sha }}
      - uses: yshui/git-clang-format-lint@27f3890c6655216edadcc2759110b9c127c74786 # v1.17
        with:
          base: ${{ github.event.pull_request.base.sha }}
